name: bambi_jss
channels:
  - defaults
  - conda-forge
dependencies:
  - arviz=0.12.0
  - bambi=0.8.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - jupyter_client=7.2.2
  - jupyterlab
  - jupyter_core=4.10.0
  - pip=21.2.4
  - pymc3=3.11.5
  - python=3.9.12
  - watermark
